# Generated by Django 4.2.5 on 2023-09-24 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=255)),
                ('potential_emission_reduction', models.FloatField()),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.factor')),
            ],
        ),
    ]
