# Generated by Django 4.2.5 on 2023-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='potential_emission_reduction',
            new_name='potential_reduction_percentage',
        ),
    ]
