# Generated by Django 4.2.5 on 2023-09-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_potential_emission_reduction_tips_potential_reduction_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='desc_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='desc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='desc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tips',
            name='desc_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
